export const actionTypes = {
  ADD_POST: 'ADD_POST',
  REMOVE_POST: 'REMOVE_POST',
  EDIT_POST: 'EDIT_POST',
  SAVE_POSTS: 'SAVE_POSTS',
  SAVE_POST: 'SAVE_POST',
  IS_FORM_REQUEST_PENDING: 'IS_FORM_REQUEST_PENDING',
  IS_REMOVE_REQUEST_PENDING: 'IS_REMOVE_REQUEST_PENDING'
};
